#!/bin/bash

echo "📝 Manual Token Update Instructions"
echo ""
echo "Current config file location:"
echo "/Users/trefgare/Library/Application Support/Claude/claude_desktop_config.json"
echo ""
echo "To update the token manually:"
echo ""
echo "1. Open the config file:"
echo "   open \"/Users/trefgare/Library/Application Support/Claude/claude_desktop_config.json\""
echo ""
echo "2. Find this line:"
echo "   \"HAMMERTECH_JWT_TOKEN\": \"eyJhbGci...your-current-token...\""
echo ""
echo "3. Replace the token value between the quotes with your new token"
echo ""
echo "4. Optionally update the region:"
echo "   \"HAMMERTECH_REGION\": \"au\"  // change to \"us\" or \"eu\" if needed"
echo ""
echo "5. Save the file (Cmd+S)"
echo ""
echo "6. Restart Claude Desktop:"
echo "   - Quit Claude Desktop completely (Cmd+Q)" 
echo "   - Reopen Claude Desktop"
echo "   - Look for the 🔧 hammer icon"
echo ""
echo "🎯 Quick command to open config file:"
echo "open \"/Users/trefgare/Library/Application Support/Claude/claude_desktop_config.json\""